export const CHANGE_CANVAS_WIDTH = "CANVAS_WIDTH";
export const CANVAS_MOBILE_BTTN = "MOBILE_BTTN";
export const CANVAS_REDISPLAY_MOBILE_BTTN = "DISPLAY_MOBILE_BTTN";
export const SCREEN_SIZE = "SCREEN SIZE";
export const SIDEBAR_CANVAS_RESIZE = "SIDEBAR_CANVAS_RESIZE";
export const CANVAS_COLOR = "SET_CANVAS_COLOR";
