export const CHANGE_CANVAS_WIDTH = "CANVAS_WIDTH";
export const CANVAS_MOBILE_BTTN = "MOBILE_BTTN";
export const CANVAS_REDISPLAY_MOBILE_BTTN = "DISPLAY_MOBILE_BTTN";
export const SCREEN_WIDTH = "SCREEN_WIDTH";
export const SCREEN_HEIGHT = "SCREEN_HEIGHT";
export const SCREEN_SIZE = "SCREEN SIZE";
